note = lib.mkResource {
  provider = "aws";
  type = "aws_s3_object";
  name = "note";
  config = {
    bucket = bucket.refAttr "id";
    key = "hello-from-nix.txt";
    content = lib.str [
      "This file's content was generated by Nix.\n"
      "It is stored in the bucket named: "
      (bucket.refAttr "id")
      "\n"
    ];
    content_type = "text/plain";
  };
};
